name: CI to Docker Hub

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: pip install -r ./app/requirements.txt

      - name: Tests
        run: pytest ./app
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and up dev
        run: docker-compose up -d
        
      - name: Build and up prod
        run: docker-compose -f docker-compose.prod.yml up -d
